import Head from 'next/head'
// import Image from 'next/image'
import styles from '../styles/Home.module.css'
// import Navbar from '../components/Navbar'
// import Footer from '../components/Footer'
// import axios from 'axios'
// axios.defaults.baseURL = 'http://127.0.0.1:8000/';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Navbar trytry</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Navbar/> */}
      {/* <h1>
        hello
      </h1> */}
      {/* <Footer/> */}
    </div>
  )
}
